### ISSUE TITLE
Modified uhttpd

### ISSUE THREAD

**Issue by nunojpg** [mkschreder/mks-openwrt-feed#3]
Does this feed installs the required uhttpd version when Juci is selected?

I've been unable to run Juci with current openwrt trunk and the root webpage just returns the index:

Index of /

../
modified: Thu, 01 Jan 1970 00:00:09 GMT
directory - 0.00 kbyte

cgi-bin/
modified: Wed, 30 Dec 2015 12:22:50 GMT
directory - 0.06 kbyte

css/
modified: Wed, 30 Dec 2015 12:22:50 GMT
directory - 0.42 kbyte

fonts/
modified: Wed, 30 Dec 2015 12:22:50 GMT
directory - 0.21 kbyte

img/
modified: Wed, 30 Dec 2015 12:22:50 GMT
directory - 0.42 kbyte

js/
modified: Wed, 30 Dec 2015 12:22:50 GMT
directory - 0.88 kbyte

config.json.gz
modified: Mon, 28 Dec 2015 04:56:33 GMT
application/x-gzip - 0.16 kbyte

index.html.gz
modified: Mon, 28 Dec 2015 04:56:33 GMT
application/x-gzip - 0.57 kbyte

reboot.html.gz
modified: Mon, 28 Dec 2015 04:56:33 GMT
application/x-gzip - 0.32 kbyte

**Comment by mkschreder** [comment]
You should install feed with -f option on CC to get package overrides
properly installed.

**Comment by nunojpg** [comment]
I was using the -f option and had some packages replaced. I was using branch master of this repository. I see other branches have uhttpd.

Anyway I've been unable to put it to work, also trying with your repository juciwrt.

There are some many repositories and branches and they probably have broken dependencies at this time.

If you have some minutes maybe you could try to do a clean build of juci on top of git://git.openwrt.org/openwrt.git and add the instructions as a readme to this repository...

And...thanks for the great work, I'm really excited to give it a try.

**Comment by mkschreder** [comment]
Ah you should use latest 1.15.12 branch. I will update build instructions
after new years..

**Comment by mkschreder** [comment]
Just a note: the last version using modified uhttpd is 2.16.02. It is also one of the stable versions that has worked smoothely with all it's limitations and all. Current version is 2.16.04 and it continues development of new backend. It has not been officially in testing yet though and customers that were using juci since the project started still base their work on the old system. This is why I tend to backport important changes back to the 2.16.02 right now. If you want a stable build then that version is an option for a while untill the new backend gets it's good share of testing and can be considered stable.
