### ISSUE TITLE
Feed

### ISSUE THREAD

**Issue by ShalokShalom** [mkschreder/mks-openwrt-feed#30]
What is this?

Is this still up to date?

What is it supposed to be?

**Comment by mkschreder** [comment]
This is the feed that contains all juci packages. Check the bootstrap
script here which shows how to properly build openwrt with juci. This is
last tested on OpenWRT DD. I do not have time to update the scripts right
now so I would encourage other people to take what is available and adopt
it to latest versions of lighttpd, libwebsocket and openwrt.

This feed contains all the packages that juci needs and packages that juci
needs to override (possibly with much older versions) in order to work.
