### ISSUE TITLE
jucid doesn't compile

### ISSUE THREAD

**Issue by nunojpg** [mkschreder/mks-openwrt-feed#4]
This jucid package version is not compiling.

juci.c:206:13: error: 'GLOB_TILDE' undeclared (first use in this function)
  glob(path, GLOB_TILDE, NULL, &glob_result);

Probably it is using a outdated jucid version.

**Comment by mkschreder** [comment]
musl?

Set that parameter to 0 for now. You can investigate alternatives later if
you want to use ~ as shortcut for use home directory in path passed to
glob().

**Comment by nunojpg** [comment]
I was trying with trunk, that uses mull. Now I tried with 15.05 and it also produces a bunch of errors, like:

juci_ws_server.c:119:56: error: 'enum lws_callback_reasons' declared inside parameter list [-Werror]
 static int _ubus_socket_callback(struct lws *wsi, enum lws_callback_reasons reason, void *_user, void *in, size_t len){

**Comment by mkschreder** [comment]
Which branch of the feed? Latest is v2.16.03.

https://github.com/mkschreder/juci-openwrt-feed/commits/v2.16.03

**Comment by nunojpg** [comment]
Actually I was trying with master, but with v2.16.03 the error is the same. The error is when compiling jucid 49c573252ed8a1c0972d241a30364d717237b31a. 

I'm not sure who is requesting -Werror, if it is your configure file or if it is openwrt. Anyway I don't understand why don't you have the same error.

Just to confirm: openwrt 15.05 (current HEAD) and you also get toolchain gcc-4.8-linaro_uClibc-0.9.33.2?

**Comment by subixonfire** [comment]
using feed v2.16.03 doesn't compile for me...
log: http://pastebin.com/ytURxP67

**Comment by mkschreder** [comment]
You either did not select or did not install libwebsockets package. Most probably you simply did not install it. Try installing all packages from the feed.

**Comment by nunojpg** [comment]
./scripts/feeds install -f -p juci -a
Installing all packages from feed juci.
Installing package 'libwebsockets'
Installing package 'lighttpd'

Well, I see this, but then at menuconfig I can't find libwebsockets, but there is libwebsockets-openssl and libwebsockets-cyassl. But I see you have those commented out at your makefile. So, maybe there is some problem with the libwebsockets makefile?

**Comment by mkschreder** [comment]
No it is because there is probably a different libwebsockets somewhere.
Whenever you have custom feeds you should always install them first before
you install any other packages. Package overrides don't work for feeds,
however if a package is already installed it, it will not be installed
again. Therefore feeds should be installed in order from custom to generic
- and openwrt feeds last.
  On 13 Apr 2016 01:51, "Nuno Goncalves" notifications@github.com wrote:

./scripts/feeds install -f -p juci -a
Installing all packages from feed juci.
Installing package 'libwebsockets'
Installing package 'lighttpd'

Well, I see this, but then at menuconfig I can't find libwebsockets, but
there is libwebsockets-openssl and libwebsockets-cyassl. But I see you have
those commented out at your makefile. So, maybe there is some problem with
the libwebsockets makefile?

**Comment by nunojpg** [comment]
Thanks, that was it. Now I face issue #6.
